# Generated by Django 4.0.4 on 2022-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0003_alter_manga_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='published',
            field=models.DateField(),
        ),
    ]
