# Generated by Django 4.0.4 on 2022-06-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0004_alter_manga_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
