# Generated by Django 4.0.4 on 2022-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0007_alter_notices_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
