# Generated by Django 4.0.4 on 2022-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0008_alter_notices_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='background',
            field=models.TextField(default='Sin Antecedentes'),
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(default='Sin Descripcion'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
