# Generated by Django 4.0.4 on 2022-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0009_manga_background_manga_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
