# Generated by Django 5.2.4 on 2025-07-03 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MAN', 'Manga')], max_length=5)),
                ('volumenes', models.IntegerField()),
                ('published', models.DateField()),
                ('description', models.TextField(default='Sin Descripcion')),
                ('background', models.TextField(default='Sin Antecedentes')),
                ('status', models.CharField(choices=[('FIN', 'Finished'), ('PUB', 'Publishing')], max_length=10)),
                ('genres', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fundation_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='Bienvenido', max_length=120)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('MOV', 'Movie'), ('TV', 'Tv'), ('ONA', 'Ona'), ('OVA', 'Ova')], max_length=5)),
                ('episodes', models.IntegerField()),
                ('relase_date', models.DateField()),
                ('genres', models.CharField(max_length=70)),
                ('duration', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('backgroun', models.TextField(default='Sin Antecedentes')),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='app.studios')),
            ],
        ),
    ]
